name: dudv_base
description: Model–view–presenter (MVP) is a derivation of the model–view–controller (MVC) architectural pattern, and is used mostly for building user interfaces.
version: 1.1.7+13
homepage: https://github.com/beheobong/dudv_base

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^10.0.0
  fluttertoast: ^8.0.9
  logger: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  analyzer: ^4.2.0


assets:
    - assets/icons_ios/`
  
