name: dudv_base
description: Model–view–presenter (MVP) is a derivation of the model–view–controller (MVC) architectural pattern, and is used mostly for building user interfaces.
version: 1.0.0
homepage: https://github.com/beheobong/dudv_base

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^8.1.4+2
  fluttertoast: ^8.0.8
  dio: ^4.0.0
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


assets:
    - assets/icons_ios/
  
